### ISSUE TITLE
java_buildpack is not installed by default

### ISSUE THREAD

**Issue by sushiandbeer** [enaml-ops/ert-plugin#4]
java_buildpack is not installed.  It should be installed by default and it also causes acceptance tests to fail.

**Comment by xchapter7x** [comment]
this should be fixed in https://github.com/enaml-ops/ert-plugin/releases/tag/v0.0.7

**Comment by sushiandbeer** [comment]
The installed java build pack name is incorrect.  It is `java-offline-buildpack`, but should be `java_buildpack_offline`.

**Comment by sushiandbeer** [comment]
The incorrect java build pack name causes acceptance tests to fail.  I manually corrected the name and verified CATS succeeds.

**Comment by xchapter7x** [comment]
corrected in commit: https://github.com/enaml-ops/ert-plugin/commit/4f95c50b5369835d9dcb118778861b700d0cde39


should make it in the next release

**Comment by xchapter7x** [comment]
https://github.com/enaml-ops/ert-plugin/releases/tag/v0.0.11
